### ISSUE TITLE
Question: Is it sane to infer errors?

### ISSUE THREAD

**Issue by KATT** [KATT/trpc-procedure-play#28]
Please discuss

How useful is it really? Unexpected errors still needs handling.

- https://github.com/trpc/v10-playground/pull/17#issuecomment-1019950361
- https://github.com/trpc/v10-playground/pull/17#issuecomment-1020717959

**Comment by mgreenw** [comment]
I don't think it's _that_ useful, especially because it's possible to already make a "generic" error handler to render all of the trpc error codes as well as page-specific error handlers for "not found" or "bad request", etc. Definitely not worth breaking changes, but if it could be implemented with good performance and without breaking changes I'd be open to it!

**Comment by KATT** [comment]
Note gonna do this for now.
